### ISSUE TITLE
Language mismatch

### ISSUE THREAD

**Issue by fabianlupa** [dominikpanzer/ABAP-Lift-Pass-Pricing-Kata#1]
Hi Dominik,

it appears the abapGit main language of the repo is german while all objects are maintained with main language english?

![image](https://user-images.githubusercontent.com/5270359/215984666-82dce081-0d94-474e-bc84-e7de753a2d1f.png)

![image](https://user-images.githubusercontent.com/5270359/215984730-caf55c13-6d1a-428d-b7d7-14a3795ddf82.png)

![image](https://user-images.githubusercontent.com/5270359/215984884-52584960-28fb-46df-95f5-db99431db088.png)

I cannot pull when logged in in english but when logged in in german I get all these language mismatch popups. Shouldn't the abapGit main language be changed to E?

**Comment by fabianlupa** [comment]
I also get some diffs I cannot get rid of. I am pulling on a S/4HANA OnPremise 2021 system.

![image](https://user-images.githubusercontent.com/5270359/215985492-1a916db4-df83-42dc-874d-c3503915cbfc.png)

**Comment by dominikpanzer** [comment]
regarding the diffs... seems to be the same problem like here: https://github.com/dominikpanzer/ABAP-Meterdata-Manager/issues/1 I will check it.

**Comment by dominikpanzer** [comment]
could you please check if it works for you now? thanks

**Comment by fabianlupa** [comment]
Hi, I'll check probably the week after next when the system is available again, just as a heads up.

**Comment by dominikpanzer** [comment]
np, happy easter to you and your family

**Comment by fabianlupa** [comment]
It now works just fine 👍
